services:
  postgres:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - pg_data:/var/lib/postgresql
    networks:
      - backend

  api:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 3000:3000
    env_file:
      - path: ./.env
        required: true
    volumes:
      - ./:/app
      - /app/node_modules
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  pg_data:
    driver: local
