services:
  pgsql:
    image: postgres:latest
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - fastify_forge_pg_data:/var/lib/postgresql
    networks:
      - fastify-forge-network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d ${POSTGRES_DB}']
      interval: 30s
      timeout: 20s
      retries: 3

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: fastify-forge-pgadmin
    ports:
      - ${PGADMIN_DEFAULT_PORT}:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    networks:
      - fastify-forge-network
    volumes:
      - fastify_forge_pgadmin_data:/var/lib/pgadmin

  api:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 3000:3000
    env_file:
      - path: ./.env
        required: true
    volumes:
      - ./:/app
      - /app/node_modules
    networks:
      - fastify-forge-network

networks:
  fastify-forge-network:
    driver: bridge

volumes:
  fastify_forge_pg_data:
    driver: local
  fastify_forge_pgadmin_data:
    driver: local
