packages:
  - "apps/*"
  - "packages/*"

catalog:
  "@types/node": ^24.3.0
  better-auth: ^1.3.4
  drizzle-kit: ^0.31.4
  drizzle-orm: ^0.44.5
  eslint: ^9.34.0
  fastify: ^5.5.0
  fastify-plugin: ^5.0.1
  pino: ^10.0.0
  pino-pretty: ^13.1.1
  typescript: ^5.9.2
  zod: 4.1.13
